import type { L } from "@/lib/i18n/localized";

/**
 * GENERATED by scripts/prepare-images.mjs — do not edit by hand.
 *
 * Every image in public/images/ with its real dimensions and the alt text that
 * shipped with it, in both languages. Regenerate with:
 *   node scripts/prepare-images.mjs <path-to-pack>
 *
 * Provenance: these are AI-generated conceptual visuals. They do not document
 * real clients, staff, premises or completed commissions — see docs/SLIKE.md.
 */
export type DemoImage = {
  src: string;
  width: number;
  height: number;
  /** object-position starting points from the delivered manifest. */
  focus: { desktop: string; mobile: string };
  alt: L;
};

export const images = {
  "lipa-hero": {
    src: "/images/lipa/lipa-hero.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "55% 50%" },
    alt: {
      bs: "Svijetao prostor dentalne ordinacije s kadulja zelenim detaljima i drvenim elementima.",
      de: "Heller Behandlungsraum mit salbeigrünen Details und Holzelementen.",
    },
  },
  "lipa-recepcija": {
    src: "/images/lipa/lipa-recepcija.webp",
    width: 1122,
    height: 1402,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Recepcija s hrastovim pultom, zelenim stolicama i toplim prirodnim svjetlom.",
      de: "Empfang mit Eichentheke, grünen Stühlen und warmem Tageslicht.",
    },
  },
  "lipa-tehnologija": {
    src: "/images/lipa/lipa-tehnologija.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Bijeli intraoralni skener na svijetloj radnoj površini.",
      de: "Weißer Intraoralscanner auf einer hellen Arbeitsfläche.",
    },
  },
  "lipa-prevencija": {
    src: "/images/lipa/lipa-prevencija.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Četkice za zube i zubni konac na svijetloj kamenoj površini.",
      de: "Zahnbürsten und Zahnseide auf einer hellen Steinfläche.",
    },
  },
  "hrast-kuhinja": {
    src: "/images/hrast/hrast-kuhinja.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "58% 50%" },
    alt: {
      bs: "Kuhinja s drvenim frontama i kamenim ostrvom u toplom dnevnom svjetlu.",
      de: "Küche mit Holzfronten und einer Steininsel im warmen Tageslicht.",
    },
  },
  "hrast-plakar": {
    src: "/images/hrast/hrast-plakar.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Ugradbeni hrastov plakar s otvorenim središnjim dijelom i klupom.",
      de: "Einbauschrank aus Eiche mit offenem Mittelteil und einer Sitzbank.",
    },
  },
  "hrast-sto": {
    src: "/images/hrast/hrast-sto.webp",
    width: 1122,
    height: 1402,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Drveni trpezarijski sto sa zaobljenim uglovima i tapaciranim stolicama.",
      de: "Esstisch aus Holz mit abgerundeten Ecken und gepolsterten Stühlen.",
    },
  },
  "hrast-spoj-detalj": {
    src: "/images/hrast/hrast-spoj-detalj.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Krupni kadar drvenog spoja na uglu hrastove ladice.",
      de: "Nahaufnahme einer Holzverbindung an der Ecke einer Eichenschublade.",
    },
  },
  "hrast-radionica": {
    src: "/images/hrast/hrast-radionica.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Ruke majstora koji obrađuje rub drvene ploče u radionici.",
      de: "Hände bei der Bearbeitung einer Holzkante in einer Werkstatt.",
    },
  },
  "hrast-materijal-hrast": {
    src: "/images/hrast/hrast-materijal-hrast.webp",
    width: 900,
    height: 900,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Uzorak svijetlog hrastovog drveta na neutralnoj podlozi.",
      de: "Muster aus hellem Eichenholz auf neutralem Hintergrund.",
    },
  },
  "hrast-materijal-orah": {
    src: "/images/hrast/hrast-materijal-orah.webp",
    width: 900,
    height: 900,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Uzorak tamnog orahovog drveta na neutralnoj podlozi.",
      de: "Muster aus dunklem Walnussholz auf neutralem Hintergrund.",
    },
  },
  "hrast-materijal-mat-bijela": {
    src: "/images/hrast/hrast-materijal-mat-bijela.webp",
    width: 900,
    height: 900,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Uzorak mat bijele ploče na neutralnoj podlozi.",
      de: "Muster einer mattweißen Platte auf neutralem Hintergrund.",
    },
  },
  "meridijan-hero": {
    src: "/images/meridijan/meridijan-hero.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Mirna prostorija za sastanke s kamenim stolom i tamnoplavim stolicama.",
      de: "Ruhiger Besprechungsraum mit Steintisch und dunkelblauen Stühlen.",
    },
  },
  "meridijan-analiza": {
    src: "/images/meridijan/meridijan-analiza.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Kalkulator, bilježnica i tamnoplava mapa na radnom stolu.",
      de: "Taschenrechner, Notizbuch und dunkelblaue Mappe auf einem Arbeitstisch.",
    },
  },
  "meridijan-radionica": {
    src: "/images/meridijan/meridijan-radionica.webp",
    width: 1536,
    height: 1024,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Ruke dvije osobe koje raspoređuju kartice tokom radnog sastanka.",
      de: "Hände zweier Personen beim Ordnen von Karten in einem Workshop.",
    },
  },
  "meridijan-plan": {
    src: "/images/meridijan/meridijan-plan.webp",
    width: 1122,
    height: 1402,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Otvorena tamnoplava mapa s bilježnicom, razdjelnicima i olovkom.",
      de: "Geöffnete dunkelblaue Mappe mit Notizheft, Trennblättern und Stift.",
    },
  },
  "most-most-skulptura": {
    src: "/images/most/most-most-skulptura.webp",
    width: 1400,
    height: 933,
    focus: { desktop: "60% 50%", mobile: "65% 50%" },
    alt: {
      bs: "Metalni luk između tamnozelenih blokova kao vizualni motiv mosta.",
      de: "Metallbogen zwischen dunkelgrünen Blöcken als visuelles Brückenmotiv.",
    },
  },
  "most-proces-dizajna": {
    src: "/images/most/most-proces-dizajna.webp",
    width: 1400,
    height: 933,
    focus: { desktop: "50% 50%", mobile: "50% 50%" },
    alt: {
      bs: "Radna površina sa skicama web stranice, uzorcima boja i priborom za dizajn.",
      de: "Arbeitsfläche mit Website-Skizzen, Farbmustern und Gestaltungswerkzeugen.",
    },
  },
} as const satisfies Record<string, DemoImage>;

export type ImageKey = keyof typeof images;
