import type { Locale } from "@/lib/i18n/config";

export const positioning = {
  bs: {
    workTitle: "Iza svakog dizajna stoji razlog.",
    workLead: "Tri samostalno izrađena demo koncepta. Tri različita puta od interesa do konkretnog upita.",
    problem: "Problem", solution: "Naše rješenje", effect: "Očekivana korist",
    disclosure: "Prikazujemo funkcionalne koncepte, ne klijentske rezultate. Navedene koristi su ciljevi dizajna, bez tvrdnji o izmjerenom rastu.",
    cases: [
      { problem: "Kupac teško zamišlja konačni namještaj.", solution: "Konfigurator prostora, materijala i dimenzija.", effect: "Konkretniji zahtjev prije prvog razgovora." },
      { problem: "Pacijent ne zna koju uslugu odabrati.", solution: "Izbor usluge i termina kroz jasne korake.", effect: "Manje nejasnoća oko prvog dolaska." },
      { problem: "Vlasnik firme ne zna odakle početi.", solution: "Kratka procjena usmjerava na odgovarajuću uslugu.", effect: "Prvi razgovor s jasnije postavljenim prioritetom." },
    ],
    whyEyebrow: "ZAŠTO MOST STUDIO",
    whyTitle: "Web treba olakšati odluku.",
    whyLead: "Kada ponuda nije jasna, izbor je težak, a kontakt skriven, posjetilac lako odustane. Zato prvo oblikujemo put do upita, pa tek onda izgled.",
    reasons: [
      ["Posao prije piksela", "Krećemo od vaše ponude, kupca i pitanja na koja web mora odgovoriti."],
      ["Odluke koje možete pratiti", "Prije izrade usklađujemo strukturu i smjer. Znate šta ulazi u obim, cijenu i rok."],
      ["Funkcije koje možete isprobati", "Pregledate stvarne tokove na mobitelu i računaru prije objave."],
    ],
    craftTitle: "Šta stoji iza dobrog weba",
    craft: [
      ["UX i sadržaj", "Jasna ponuda, razumljiva navigacija i smislen sljedeći korak."],
      ["SEO i struktura", "Naslovi, metapodaci, sitemap i strukturirani podaci gdje imaju smisla."],
      ["Brzina i mobitel", "Optimizovane slike i raspored prilagođen različitim ekranima."],
      ["Pristupačnost", "Kontrast, vidljiv fokus, označena polja i navigacija tastaturom."],
      ["Jasni odgovori · AEO/GEO", "Precizan sadržaj koji ljudi i sistemi za pretragu mogu lakše razumjeti. Bez obećanja o rangiranju."],
      ["Mjerenje", "Praćenje ključnih klikova i koraka, prema cilju i dogovorenom obimu projekta."],
    ],
    contactTitle: "Hajde da vaš web dobije jasan zadatak.",
    contactLead: "Opišite posao i šta želite poboljšati. Na osnovu toga možemo razgovarati o rješenju, obimu i cijeni.",
    nextTitle: "Šta slijedi nakon upita?",
    next: ["Razjasnimo cilj i potrebne funkcije.", "Predložimo smjer i obim projekta.", "Dogovorimo ponudu i rok prije početka."],
    direct: "Radije biste kratku poruku?", inquiry: "Pripremite projektni upit", optional: "opcionalno",
    name: "Ime", company: "Firma / djelatnost", website: "Postojeća stranica", reply: "Email ili telefon za odgovor",
    need: "Šta vam treba?", needs: ["Nova web stranica", "Redizajn", "Webshop", "Trebam savjet"],
    details: "Šta želite da vaš web radi bolje?", placeholder: "Npr. prikazati naše usluge i omogućiti kupcu da zatraži ponudu.",
    prepare: "Pregledaj upit", preview: "Vaš upit", edit: "Uredi podatke", copy: "1. Kopiraj upit", copied: "Upit je kopiran", instagram: "2. Otvori Instagram", email: "Radije email? Otvori poruku",
    note: "Pripremite poruku, kopirajte je i pošaljite nam na Instagramu. Obrazac je ne šalje automatski.",
    privacy: "Uneseni podaci ostaju u ovom pregledniku dok ih sami ne pošaljete. Ne unosite povjerljive podatke.",
    failed: "Kopiranje nije uspjelo. Označite poruku ispod i kopirajte je ručno.",
    ready: "Pregledajte i kopirajte upit, pa ga zalijepite u razgovor s našim profilom. Upit primamo tek kada ga pošaljete. Ako odaberete email, završite slanje u svojoj email aplikaciji.",
  },
  de: {
    workTitle: "Hinter jedem Design steht ein Grund.",
    workLead: "Drei selbst entwickelte Demokonzepte. Drei unterschiedliche Wege vom Interesse zur konkreten Anfrage.",
    problem: "Problem", solution: "Unsere Lösung", effect: "Angestrebter Nutzen",
    disclosure: "Wir zeigen funktionierende Konzepte, keine Kundenergebnisse. Der beschriebene Nutzen ist ein Designziel und keine Behauptung über gemessenes Wachstum.",
    cases: [
      { problem: "Kunden können sich das fertige Möbel schwer vorstellen.", solution: "Ein Konfigurator für Möbelart, Material und Maße.", effect: "Eine konkretere Anfrage vor dem ersten Gespräch." },
      { problem: "Patienten wissen nicht, welche Leistung sie wählen sollen.", solution: "Leistung und Termin in verständlichen Schritten auswählen.", effect: "Mehr Klarheit vor dem ersten Praxisbesuch." },
      { problem: "Unternehmer wissen nicht, wo sie anfangen sollen.", solution: "Eine kurze Einschätzung führt zur passenden Leistung.", effect: "Ein Erstgespräch mit klarer gesetzten Prioritäten." },
    ],
    whyEyebrow: "WARUM MOST STUDIO",
    whyTitle: "Eine Website soll Entscheidungen erleichtern.",
    whyLead: "Ein unverständliches Angebot, schwierige Auswahl und versteckte Kontaktwege können Besucher verlieren. Deshalb gestalten wir zuerst den Weg zur Anfrage und dann den Auftritt.",
    reasons: [
      ["Ihr Geschäft zuerst", "Wir beginnen mit Ihrem Angebot, Ihren Kunden und den Fragen, die Ihre Website beantworten muss."],
      ["Nachvollziehbare Entscheidungen", "Vor der Umsetzung stimmen wir Struktur und Richtung ab. Umfang, Preis und Zeitplan werden klar vereinbart."],
      ["Funktionen zum Ausprobieren", "Sie prüfen echte Abläufe auf Handy und Computer vor der Veröffentlichung."],
    ],
    craftTitle: "Was eine gute Website ausmacht",
    craft: [
      ["UX und Inhalte", "Ein klares Angebot, verständliche Navigation und ein sinnvoller nächster Schritt."],
      ["SEO und Struktur", "Überschriften, Metadaten, Sitemap und strukturierte Daten, wo sie sinnvoll sind."],
      ["Tempo und Mobilgeräte", "Optimierte Bilder und Layouts für unterschiedliche Bildschirmgrößen."],
      ["Barrierearme Bedienung", "Kontraste, sichtbarer Fokus, beschriftete Felder und Tastaturnavigation."],
      ["Klare Antworten · AEO/GEO", "Präzise Inhalte, die Menschen und Suchsysteme leichter verstehen. Ohne Rankingversprechen."],
      ["Messbarkeit", "Wichtige Klicks und Schritte messen, abgestimmt auf Ziel und vereinbarten Projektumfang."],
    ],
    contactTitle: "Geben wir Ihrer Website eine klare Aufgabe.",
    contactLead: "Beschreiben Sie Ihr Geschäft und was Sie verbessern möchten. So können wir über Lösung, Umfang und Preis sprechen.",
    nextTitle: "Wie geht es nach der Anfrage weiter?",
    next: ["Ziel und benötigte Funktionen klären.", "Richtung und Projektumfang vorschlagen.", "Angebot und Zeitplan vor dem Start abstimmen."],
    direct: "Lieber eine kurze Nachricht?", inquiry: "Projektanfrage vorbereiten", optional: "optional",
    name: "Name", company: "Unternehmen / Tätigkeit", website: "Bestehende Website", reply: "E-Mail oder Telefonnummer für die Antwort",
    need: "Was benötigen Sie?", needs: ["Neue Website", "Relaunch", "Onlineshop", "Beratung"],
    details: "Was soll Ihre Website besser machen?", placeholder: "Z. B. unsere Leistungen vorstellen und eine Angebotsanfrage ermöglichen.",
    prepare: "Anfrage prüfen", preview: "Ihre Anfrage", edit: "Angaben bearbeiten", copy: "1. Anfrage kopieren", copied: "Anfrage kopiert", instagram: "2. Instagram öffnen", email: "Lieber per E-Mail? Nachricht öffnen",
    note: "Bereiten Sie die Nachricht vor, kopieren Sie sie und senden Sie sie auf Instagram. Das Formular versendet sie nicht automatisch.",
    privacy: "Ihre Angaben bleiben in diesem Browser, bis Sie sie selbst senden. Bitte keine vertraulichen Daten eingeben.",
    failed: "Kopieren fehlgeschlagen. Markieren Sie die Nachricht unten und kopieren Sie sie manuell.",
    ready: "Prüfen und kopieren Sie die Anfrage und fügen Sie sie im Chat mit unserem Profil ein. Wir erhalten sie erst nach dem Versand. Wenn Sie E-Mail wählen, schließen Sie den Versand in Ihrer E-Mail-App ab.",
  },
} satisfies Record<Locale, unknown>;
