/**
 * GENERATED by scripts/capture-demos.mjs — do not edit by hand.
 *
 * Screenshots of the implemented demo pages, one pair per language, used by
 * the MOST hero, the portfolio cards and the concept pages. Regenerate after
 * any change to a demo:
 *   npm run build && npm run start
 *   BASE_URL=http://127.0.0.1:3000 node scripts/capture-demos.mjs
 */
export type Shot = { src: string; width: number; height: number };

export const shots = {
  "ordinacija-lipa-bs-desktop": { src: "/images/snimci/ordinacija-lipa-bs-desktop.webp", width: 1600, height: 1000 },
  "ordinacija-lipa-de-desktop": { src: "/images/snimci/ordinacija-lipa-de-desktop.webp", width: 1600, height: 1000 },
  "stolarija-hrast-bs-desktop": { src: "/images/snimci/stolarija-hrast-bs-desktop.webp", width: 1600, height: 1000 },
  "stolarija-hrast-de-desktop": { src: "/images/snimci/stolarija-hrast-de-desktop.webp", width: 1600, height: 1000 },
  "meridijan-savjetovanje-bs-desktop": { src: "/images/snimci/meridijan-savjetovanje-bs-desktop.webp", width: 1600, height: 1000 },
  "meridijan-savjetovanje-de-desktop": { src: "/images/snimci/meridijan-savjetovanje-de-desktop.webp", width: 1600, height: 1000 },
  "ordinacija-lipa-bs-mobile": { src: "/images/snimci/ordinacija-lipa-bs-mobile.webp", width: 780, height: 1688 },
  "ordinacija-lipa-de-mobile": { src: "/images/snimci/ordinacija-lipa-de-mobile.webp", width: 780, height: 1688 },
  "stolarija-hrast-bs-mobile": { src: "/images/snimci/stolarija-hrast-bs-mobile.webp", width: 780, height: 1688 },
  "stolarija-hrast-de-mobile": { src: "/images/snimci/stolarija-hrast-de-mobile.webp", width: 780, height: 1688 },
  "meridijan-savjetovanje-bs-mobile": { src: "/images/snimci/meridijan-savjetovanje-bs-mobile.webp", width: 780, height: 1688 },
  "meridijan-savjetovanje-de-mobile": { src: "/images/snimci/meridijan-savjetovanje-de-mobile.webp", width: 780, height: 1688 },
} as const satisfies Record<string, Shot>;

export type ShotKey = keyof typeof shots;
