/**
 * Screenshots the real demo pages for the MOST hero, the portfolio cards and
 * the concept pages.
 *
 *   npm run build && npm run start            # in another shell
 *   BASE_URL=http://127.0.0.1:3000 node scripts/capture-demos.mjs
 *
 * These are captures of the implemented pages, not mock-ups: what a card shows
 * is what opens when you click it. Photographs of rooms are never a substitute
 * for these — see docs/SLIKE.md.
 *
 * Our own demo chrome (the MOST bar) is hidden during capture so the shot
 * frames the demo site itself.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { chromium } from "@playwright/test";
import sharp from "sharp";

const BASE = process.env.BASE_URL ?? "http://127.0.0.1:3000";
const OUT = path.join(process.cwd(), "public", "images", "snimci");

const demos = [
  { slug: "ordinacija-lipa", bs: "/demo/ordinacija-lipa", de: "/de/demo/ordinacija-lipa" },
  { slug: "stolarija-hrast", bs: "/demo/stolarija-hrast", de: "/de/demo/stolarija-hrast" },
  { slug: "meridijan-savjetovanje", bs: "/demo/meridijan-savjetovanje", de: "/de/demo/meridijan-savjetovanje" },
];

const devices = {
  desktop: { width: 1440, height: 900, scale: 2, out: 1600 },
  mobile: { width: 390, height: 844, scale: 3, out: 780 },
};

await mkdir(OUT, { recursive: true });

const browser = await chromium.launch({
  ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}),
});

const entries = [];

for (const [deviceName, device] of Object.entries(devices)) {
  const context = await browser.newContext({
    viewport: { width: device.width, height: device.height },
    deviceScaleFactor: device.scale,
    // Capture the settled page, not the entrance animation.
    reducedMotion: "reduce",
  });

  for (const demo of demos) {
    for (const lang of ["bs", "de"]) {
      const page = await context.newPage();
      await page.goto(BASE + demo[lang], { waitUntil: "load" });
      await page.addStyleTag({ content: "[data-most-chrome]{display:none !important}" });
      // Wait for the photographs that are actually in frame. Anything below
      // the fold is lazy-loaded and would never fire `load`, so the wait is
      // scoped to the viewport and bounded by a timeout either way.
      await page.evaluate(async () => {
        const inFrame = Array.from(document.images).filter((img) => {
          const r = img.getBoundingClientRect();
          return r.top < window.innerHeight && r.bottom > 0 && !img.complete;
        });
        const settled = Promise.all(
          inFrame.map(
            (img) =>
              new Promise((done) => {
                img.addEventListener("load", done, { once: true });
                img.addEventListener("error", done, { once: true });
              }),
          ),
        );
        await Promise.race([settled, new Promise((done) => setTimeout(done, 8000))]);
        await Promise.race([
          document.fonts?.ready ?? Promise.resolve(),
          new Promise((done) => setTimeout(done, 3000)),
        ]);
      });
      await page.waitForTimeout(600);

      const raw = await page.screenshot({ type: "png" });
      const webp = await sharp(raw).resize({ width: device.out }).webp({ quality: 82, effort: 6 }).toBuffer();
      const meta = await sharp(webp).metadata();

      const file = `${demo.slug}-${lang}-${deviceName}.webp`;
      await writeFile(path.join(OUT, file), webp);
      entries.push({
        key: `${demo.slug}-${lang}-${deviceName}`,
        src: `/images/snimci/${file}`,
        width: meta.width,
        height: meta.height,
      });
      console.log(`${file.padEnd(46)} ${meta.width}×${meta.height}  ${(webp.length / 1024).toFixed(0)} kB`);
      await page.close();
    }
  }
  await context.close();
}

await browser.close();

const rows = entries
  .map((e) => `  "${e.key}": { src: "${e.src}", width: ${e.width}, height: ${e.height} },`)
  .join("\n");

await writeFile(
  path.join(process.cwd(), "src", "content", "shots.ts"),
  `/**
 * GENERATED by scripts/capture-demos.mjs — do not edit by hand.
 *
 * Screenshots of the implemented demo pages, one pair per language, used by
 * the MOST hero, the portfolio cards and the concept pages. Regenerate after
 * any change to a demo:
 *   npm run build && npm run start
 *   BASE_URL=http://127.0.0.1:3000 node scripts/capture-demos.mjs
 */
export type Shot = { src: string; width: number; height: number };

export const shots = {
${rows}
} as const satisfies Record<string, Shot>;

export type ShotKey = keyof typeof shots;
`,
);

console.log(`\n${entries.length} screenshots written to public/images/snimci/`);
