/**
 * Turns the delivered image pack into what the site actually ships.
 *
 *   node scripts/prepare-images.mjs <path-to-pack>
 *
 * The pack holds lossless WebP originals (~25 MB). Those are archival: this
 * script verifies each one against the manifest's SHA-256, resizes it to the
 * largest size the layout can use, re-encodes it lossy, writes it to
 * public/images/, and generates src/content/images.ts with the dimensions and
 * the BS/DE alt text from the manifest — so alt text can never drift from the
 * file it describes.
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const packRoot = process.argv[2];
if (!packRoot) {
  console.error("usage: node scripts/prepare-images.mjs <path-to-pack>");
  process.exit(1);
}

/** Largest width each role is ever displayed at, doubled for dense screens. */
const maxWidth = { lipa: 1536, hrast: 1536, meridijan: 1536, most: 1400 };
const materialWidth = 900;

const manifest = JSON.parse(await readFile(path.join(packRoot, "manifest.json"), "utf8"));
const outRoot = path.join(process.cwd(), "public", "images");
const entries = [];
let totalIn = 0;
let totalOut = 0;

for (const asset of manifest.assets) {
  const source = path.join(packRoot, asset.path);
  const buffer = await readFile(source);

  const digest = createHash("sha256").update(buffer).digest("hex");
  if (digest !== asset.sha256) {
    throw new Error(`Checksum mismatch for ${asset.file}: manifest says ${asset.sha256}, file is ${digest}`);
  }

  const isMaterial = asset.file.includes("materijal");
  const target = isMaterial ? materialWidth : (maxWidth[asset.group] ?? 1400);
  const width = Math.min(target, asset.width);

  const pipeline = sharp(buffer).resize({ width, withoutEnlargement: true });
  const out = await pipeline.webp({ quality: isMaterial ? 82 : 78, effort: 6 }).toBuffer();
  const meta = await sharp(out).metadata();

  const dir = path.join(outRoot, asset.group);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, asset.file), out);

  totalIn += buffer.length;
  totalOut += out.length;

  entries.push({
    key: asset.file.replace(/\.webp$/, ""),
    group: asset.group,
    src: `/images/${asset.group}/${asset.file}`,
    width: meta.width,
    height: meta.height,
    altBs: asset.alt_bs,
    altDe: asset.alt_de,
    title: asset.title,
    desktop: asset.desktop,
    mobile: asset.mobile,
  });

  console.log(
    `${asset.group}/${asset.file}`.padEnd(42),
    `${(buffer.length / 1024).toFixed(0)} kB → ${(out.length / 1024).toFixed(0)} kB  (${meta.width}×${meta.height})`,
  );
}

const lines = entries
  .map(
    (e) => `  "${e.key}": {
    src: "${e.src}",
    width: ${e.width},
    height: ${e.height},
    focus: { desktop: "${e.desktop}", mobile: "${e.mobile}" },
    alt: {
      bs: ${JSON.stringify(e.altBs)},
      de: ${JSON.stringify(e.altDe)},
    },
  },`,
  )
  .join("\n");

const generated = `import type { L } from "@/lib/i18n/localized";

/**
 * GENERATED by scripts/prepare-images.mjs — do not edit by hand.
 *
 * Every image in public/images/ with its real dimensions and the alt text that
 * shipped with it, in both languages. Regenerate with:
 *   node scripts/prepare-images.mjs <path-to-pack>
 *
 * Provenance: these are AI-generated conceptual visuals. They do not document
 * real clients, staff, premises or completed commissions — see docs/SLIKE.md.
 */
export type DemoImage = {
  src: string;
  width: number;
  height: number;
  /** object-position starting points from the delivered manifest. */
  focus: { desktop: string; mobile: string };
  alt: L;
};

export const images = {
${lines}
} as const satisfies Record<string, DemoImage>;

export type ImageKey = keyof typeof images;
`;

await writeFile(path.join(process.cwd(), "src", "content", "images.ts"), generated);

console.log(
  `\n${entries.length} images · ${(totalIn / 1024 / 1024).toFixed(1)} MB → ${(totalOut / 1024 / 1024).toFixed(1)} MB`,
);
