'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Minus,Plus,Search,ShoppingBag,SlidersHorizontal,Trash2,Truck,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogClose} from '@shop/components/ui/dialog';
import {Sheet,SheetContent,SheetDescription,SheetTitle,SheetClose} from '@shop/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@shop/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@shop/components/ui/radio-group';
import {Toaster} from 'sonner';
import {toast} from 'sonner';
import {products,categories,productById,money,normalize,addLines,recoverCart,subtotal,shipping,type CartLine,type Product} from '@shop/lib/catalog';
import {registerShopTools} from '@shop/lib/webmcp';
type Receipt={number:string;items:CartLine[];total:number;delivery:number;name:string};
function Picture({p,priority=false}:{p:Product;priority?:boolean}){return <img src={p.image} alt={p.name+' — '+p.color.toLowerCase()} width="396" height="396" loading={priority?'eager':'lazy'} decoding="async"/>;}
function Close({label='Zatvori'}:{label?:string}){return <DialogClose className="close-button" aria-label={label}><X size={20}/></DialogClose>;}
function Choice({value,onChange,label,options,className=''}:{value:string;onChange:(s:string)=>void;label:string;options:string[][];className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className={className} aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>;}
function Totals({amount}:{amount:number}){return <div className="totals"><div><span>Artikli</span><span>{money(amount)}</span></div><div><span>Dostava</span><span>{shipping(amount)?money(shipping(amount)):'Besplatno'}</span></div><div className="total-line"><strong>Ukupno</strong><strong>{money(amount+shipping(amount))}</strong></div></div>;}

export default function Shop(){
const [category,setCategory]=useState('Sve'),[query,setQuery]=useState(''),[sort,setSort]=useState('featured');
const [budget,setBudget]=useState('all'),[filterSize,setFilterSize]=useState('all'),[filterOpen,setFilterOpen]=useState(false);
const [selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState(''),[sizeError,setSizeError]=useState('');
const [cart,setCart]=useState<CartLine[]>(()=>{try{return recoverCart(JSON.parse(localStorage.getItem('most-demo-cart-v1')??'[]'));}catch{return [];}}),[cartOpen,setCartOpen]=useState(false);
const [checkoutOpen,setCheckoutOpen]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[formError,setFormError]=useState('');
const [guideOpen,setGuideOpen]=useState(false),[infoOpen,setInfoOpen]=useState(false);
const cartRef=useRef<CartLine[]>(cart),searchRef=useRef<HTMLInputElement>(null),submitLock=useRef(false);
const commitCart=useCallback((next:CartLine[])=>{cartRef.current=next;setCart(next);try{localStorage.setItem('most-demo-cart-v1',JSON.stringify(next));}catch{/* Private browsing can deny storage. */}},[]);
const commitAdd=useCallback((lines:CartLine[])=>{const next=addLines(cartRef.current,lines);commitCart(next);return next;},[commitCart]);

useEffect(()=>{const sync=()=>{const id=new URLSearchParams(location.hash.slice(1)).get('proizvod'),p=id?productById.get(id):undefined;setSelected(p??null);setSize(p?.sizes.length===1?p.sizes[0]:'');setSizeError('');};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
useEffect(()=>registerShopTools({getCart:()=>cartRef.current,search:(q,c)=>{setQuery(q);setCategory(c);setBudget('all');setFilterSize('all');},add:items=>{commitAdd(items);setCartOpen(true);}}),[commitAdd]);
const shown=useMemo(()=>{const found=products.filter(p=>(category==='Sve'||p.category===category)&&normalize(p.name+' '+p.category+' '+p.color).includes(normalize(query))&&(budget==='all'||p.price<=Number(budget))&&(filterSize==='all'||(p.stock[filterSize]??0)>0));return sort==='price-asc'?found.sort((a,b)=>a.price-b.price):sort==='price-desc'?found.sort((a,b)=>b.price-a.price):sort==='name'?found.sort((a,b)=>a.name.localeCompare(b.name,'bs')):found;},[category,query,sort,budget,filterSize]);
const count=cart.reduce((n,l)=>n+l.quantity,0),amount=subtotal(cart),activeFilters=Number(budget!=='all')+Number(filterSize!=='all');
const openProduct=(p:Product)=>{setSelected(p);setSize(p.sizes.length===1?p.sizes[0]:'');setSizeError('');history.replaceState(null,'',`#proizvod=${p.id}`);};
const closeProduct=()=>{setSelected(null);history.replaceState(null,'',location.pathname+location.search);};
const resetFilters=()=>{setCategory('Sve');setQuery('');setBudget('all');setFilterSize('all');};
const addSelected=()=>{if(!selected)return;if(!size){setSizeError('Odaberite veličinu prije dodavanja u korpu.');return;}try{commitAdd([{id:selected.id,size,quantity:1}]);closeProduct();setCartOpen(true);}catch(e){setSizeError((e as Error).message);}};
const changeQuantity=(line:CartLine,delta:number)=>{const p=productById.get(line.id)!,quantity=line.quantity+delta;if(quantity<1)return;if(quantity>p.stock[line.size]){toast.error('Odabrana količina nije dostupna.');return;}commitCart(cartRef.current.map(l=>l.id===line.id&&l.size===line.size?{...l,quantity}:l));};
const removeLine=(line:CartLine)=>commitCart(cartRef.current.filter(l=>!(l.id===line.id&&l.size===line.size)));
const startCheckout=()=>{if(!cartRef.current.length)return;setCartOpen(false);setReceipt(null);setFormError('');submitLock.current=false;setCheckoutOpen(true);};
const completeOrder=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(submitLock.current)return;const form=e.currentTarget;if(!form.reportValidity())return;const data=new FormData(form);for(const key of ['name','email','address','city'])if(!String(data.get(key)??'').trim()){setFormError('Popunite sva polja za probnu narudžbu.');return;}const current=cartRef.current;if(!current.length){setFormError('Korpa je prazna. Dodajte proizvod za probnu kupovinu.');return;}submitLock.current=true;const a=subtotal(current),delivery=shipping(a);setReceipt({number:`DEMO-${Date.now().toString().slice(-6)}`,items:current.map(l=>({...l})),total:a+delivery,delivery,name:String(data.get('name')).trim()});commitCart([]);};
return <>
<a className="skip-link" href="#kolekcija">Preskoči na proizvode</a>
<div className="demo-bar"><span>DEMO WEBSHOP</span><span>Isprobajte kupovinu bez plaćanja</span><a href="/#top" aria-label="Na početnu stranicu MOST Studija"><ArrowLeft size={16}/> MOST Studio</a><button onClick={()=>setInfoOpen(true)}>O ovom primjeru</button></div>
<header className="site-header"><button className="wordmark" onClick={()=>{resetFilters();window.scrollTo({top:0,behavior:'smooth'});}} aria-label="VAŠ BREND — cijela kolekcija">VAŠ BREND<span>MUŠKA ODJEĆA</span></button><nav className="top-nav" aria-label="Glavna navigacija"><button onClick={()=>{resetFilters();document.getElementById('kolekcija')?.scrollIntoView({behavior:'smooth'});}}>Kolekcija</button><button onClick={()=>{setCategory(categories[0]);document.getElementById('kolekcija')?.scrollIntoView({behavior:'smooth'});}}>Odijela i sakoi</button><button onClick={()=>setInfoOpen(true)}>O ovom primjeru</button></nav><div className="header-actions"><button className="icon-button" aria-label="Pretraži kolekciju" onClick={()=>{searchRef.current?.scrollIntoView({block:'center',behavior:'smooth'});searchRef.current?.focus();}}><Search size={21}/></button><button className="cart-button" aria-label={`Otvori korpu, ${count} artikala`} onClick={()=>setCartOpen(true)}><ShoppingBag size={21}/><span>Korpa</span><b>{count}</b></button></div></header>
<main className="page-shell"><section className="collection-intro"><div><p className="eyebrow">OD POSLOVNOG DANA DO SLOBODNOG VREMENA</p><h1>Dobar kroj.<br/><em>Pravi dojam.</em></h1></div><div className="intro-note"><span className="collection-number">01 — KOLEKCIJA</span><p>Komadi koji se lako nose.<br/>Detalji koji ostaju primijećeni.</p><span className="intro-count">50 artikala za vašu garderobu</span></div></section>
<section id="kolekcija" className="catalog" aria-label="Katalog proizvoda"><div className="category-tabs" aria-label="Kategorije">{['Sve',...categories].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}<span>{c==='Sve'?50:10}</span></button>)}</div>
<div className="catalog-toolbar"><div className="search-field"><Search size={18}/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} aria-label="Pretraži proizvode" placeholder="Pronađite svoj sljedeći komad"/>{query&&<button aria-label="Obriši pretragu" onClick={()=>setQuery('')}><X size={16}/></button>}</div><div className="toolbar-controls"><button className={'filter-button '+(activeFilters?'has-filters':'')} onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={17}/>Filteri{activeFilters>0&&<b>{activeFilters}</b>}</button><Choice value={sort} onChange={setSort} label="Sortiranje proizvoda" className="sort-select" options={[["featured","Naš izbor"],["price-asc","Cijena: niža prvo"],["price-desc","Cijena: viša prvo"],["name","Naziv: A–Ž"]]}/></div></div>
<div className="results-line"><p aria-live="polite">{shown.length} {shown.length===1?'artikal':'artikala'}<span>{category==='Sve'?'Cijela kolekcija':category}</span></p>{(activeFilters>0||query||category!=='Sve')&&<button onClick={resetFilters}>Poništi odabir <X size={13}/></button>}</div>
{shown.length?<div className="product-grid">{shown.map((p,i)=><article className="product-card" key={p.id}><button className="product-photo" aria-label={`Pogledaj ${p.name}`} onClick={()=>openProduct(p)}><Picture p={p} priority={i<4}/><span className="view-product">Pogledaj proizvod <Plus size={17}/></span></button><div className="product-meta"><div><p className="product-category">{p.category}</p><h2><button onClick={()=>openProduct(p)}>{p.name}</button></h2><p className="product-color">{p.color}</p></div><p className="product-price">{money(p.price)}</p></div></article>)}</div>:<div className="empty-state"><Search size={34} strokeWidth={1}/><h2>Nema artikala za ovaj odabir.</h2><p>Probajte drugi naziv ili promijenite filtere.</p><button className="primary-button" onClick={resetFilters}>Prikaži cijelu kolekciju</button></div>}
{shown.length>0&&<div className="catalog-end"><span>Prikazano {shown.length} od 50 artikala</span><button onClick={()=>document.getElementById('kolekcija')?.scrollIntoView({behavior:'smooth'})}>Nazad na kolekciju ↑</button></div>}</section></main>
<footer className="site-footer"><div><span className="footer-wordmark">VAŠ BREND</span><p>Primjer trgovine koju prilagođavamo vašem poslu.</p></div><div className="footer-links"><button onClick={()=>setInfoOpen(true)}>O demo trgovini</button><button onClick={()=>setGuideOpen(true)}>Vodič za veličine</button><button onClick={()=>setCartOpen(true)}>Moja korpa</button></div><div className="footer-credit"><a href="/#top">Izradio MOST Studio</a><p>Proizvodi, cijene i dostupnost su ilustrativni.<br/>Fotografije su generisane za ovaj demo.</p></div></footer>

<Dialog open={!!selected} onOpenChange={o=>{if(!o)closeProduct();}}><DialogContent className="product-dialog" showCloseButton={false}>{selected&&<><Close label="Zatvori proizvod"/><div className="detail-photo"><Picture p={selected} priority/><span>{selected.sku}</span></div><div className="detail-content"><p className="eyebrow">{selected.category}</p><DialogTitle className="detail-title">{selected.name}</DialogTitle><p className="detail-price">{money(selected.price)}</p><DialogDescription className="detail-description">{selected.description}</DialogDescription><div className="detail-color"><span>Boja</span><strong>{selected.color}</strong></div><div className="size-heading"><p>{selected.sizes.length===1?'Veličina':'Odaberite veličinu'}</p><button onClick={()=>setGuideOpen(true)}>Vodič za veličine</button></div><RadioGroup value={size} onValueChange={v=>{setSize(v);setSizeError('');}} className="size-options" aria-label="Veličina proizvoda">{selected.sizes.map(s=><label key={s} className={`size-option ${size===s?'selected':''} ${!selected.stock[s]?'unavailable':''}`}><RadioGroupItem value={s} disabled={!selected.stock[s]} aria-label={`Veličina ${s}${!selected.stock[s]?', nedostupna':''}`}/><span>{s}</span></label>)}</RadioGroup><p className="size-status">{size?<><Check size={14}/>Dostupno u odabranoj veličini</>:'Precrtane veličine trenutno nisu dostupne.'}</p>{sizeError&&<p role="alert" className="inline-error">{sizeError}</p>}<button className="primary-button add-to-cart" onClick={addSelected}><ShoppingBag size={18}/>Dodaj u korpu<ArrowRight size={18}/></button><div className="delivery-note"><Truck size={17}/><span>Demo dostava: 8 KM · besplatno od 200 KM</span></div><details className="detail-accordion"><summary>Opis i sastav <Plus size={16}/></summary><p>Materijal: {selected.fabric}. Boja: {selected.color.toLowerCase()}. Sastav je dio demo kataloga; za stvarnu trgovinu unosimo podatke proizvođača.</p></details><details className="detail-accordion"><summary>Probna kupovina <Plus size={16}/></summary><p>Možete završiti probnu narudžbu. Nema naplate, dostave ni slanja narudžbe trgovcu.</p></details></div></>}</DialogContent></Dialog>

<Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet" showCloseButton={false}><div className="panel-header"><div><SheetTitle className="panel-title">Vaša korpa <span>({count})</span></SheetTitle><SheetDescription>Vaš odabir, na jednom mjestu.</SheetDescription></div><SheetClose className="icon-button" aria-label="Zatvori korpu"><X size={22}/></SheetClose></div>{cart.length?<><div className="cart-items">{cart.map(l=>{const p=productById.get(l.id)!;return <div className="cart-item" key={l.id+l.size}><img src={p.image} alt={p.name} width="100" height="120"/><div className="cart-item-info"><h3>{p.name}</h3><p>{p.color} · {l.size}</p><strong>{money(p.price*l.quantity)}</strong><div className="cart-item-bottom"><div className="quantity-control"><button aria-label={`Smanji količinu ${p.name}, ${l.size}`} disabled={l.quantity<=1} onClick={()=>changeQuantity(l,-1)}><Minus size={14}/></button><span aria-label="Količina">{l.quantity}</span><button aria-label={`Povećaj količinu ${p.name}, ${l.size}`} disabled={l.quantity>=p.stock[l.size]} onClick={()=>changeQuantity(l,1)}><Plus size={14}/></button></div><button className="remove-button" aria-label={`Ukloni ${p.name}, ${l.size}`} onClick={()=>removeLine(l)}><Trash2 size={16}/></button></div></div></div>;})}</div><div className="cart-summary"><p className="shipping-hint">{amount<200?`Još ${money(200-amount)} do besplatne demo dostave.`:<><Check size={15}/>Besplatna demo dostava</>}</p><Totals amount={amount}/><button className="primary-button" onClick={startCheckout}>Nastavi na probnu kupovinu<ArrowRight size={17}/></button><p className="demo-note">Demo kupovina — bez naplate i slanja robe.</p><SheetClose className="continue-link">Nastavi razgledati</SheetClose></div></>:<div className="empty-cart"><ShoppingBag size={46} strokeWidth={1}/><h3>Vaša korpa čeka prvi komad.</h3><p>Odaberite proizvod i veličinu iz kolekcije.</p><SheetClose className="primary-button">Pogledaj kolekciju<ArrowRight size={17}/></SheetClose></div>}</SheetContent></Sheet>

<Sheet open={filterOpen} onOpenChange={setFilterOpen}><SheetContent className="filter-sheet" showCloseButton={false}><div className="panel-header"><div><SheetTitle className="panel-title">Vaš odabir</SheetTitle><SheetDescription>Pronađite ono što vam odgovara.</SheetDescription></div><SheetClose className="icon-button" aria-label="Zatvori filtere"><X size={22}/></SheetClose></div><div className="filter-body"><p>Cijena</p><Choice value={budget} onChange={setBudget} label="Cijena" className="full-select" options={[["all","Sve cijene"],["50","Do 50 KM"],["100","Do 100 KM"],["200","Do 200 KM"]]}/><p>Dostupna veličina</p><Choice value={filterSize} onChange={setFilterSize} label="Dostupna veličina" className="full-select" options={['all','S','M','L','XL','XXL','30','32','34','36','38','46','48','50','52','54','56','90','95','100','105','110','Univerzalna'].map(s=>[s,s==='all'?'Sve veličine':s])}/><button className="text-link" onClick={()=>{setBudget('all');setFilterSize('all');}}>Poništi filtere</button></div><div className="filter-bottom"><SheetClose className="primary-button">Prikaži {shown.length} artikala<ArrowRight size={17}/></SheetClose></div></SheetContent></Sheet>

<Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className="checkout-dialog" showCloseButton={false}><Close label="Zatvori probnu kupovinu"/>{receipt?<div className="receipt"><CheckCircle2 size={48} strokeWidth={1.3}/><p className="eyebrow">{receipt.number}</p><DialogTitle>Probna narudžba je završena.</DialogTitle><DialogDescription>{receipt.name}, ovako bi izgledala potvrda kupovine. Ništa nije naplaćeno niti poslano trgovcu.</DialogDescription><div className="receipt-items">{receipt.items.map(l=><div key={l.id+l.size}><span>{productById.get(l.id)!.name}<small>{l.size} · {l.quantity} kom.</small></span><strong>{money(productById.get(l.id)!.price*l.quantity)}</strong></div>)}<div><span>Dostava</span><span>{money(receipt.delivery)}</span></div><div className="total-line"><strong>Ukupno</strong><strong>{money(receipt.total)}</strong></div></div><DialogClose className="primary-button">Vrati se u kolekciju<ArrowRight size={18}/></DialogClose></div>:<><p className="eyebrow">JOŠ JEDAN KORAK</p><DialogTitle className="checkout-title">Probna kupovina</DialogTitle><DialogDescription>Koristite pripremljene demo podatke. Ova narudžba se ne naplaćuje i ne šalje trgovcu.</DialogDescription><form onSubmit={completeOrder} className="checkout-form"><div className="form-grid"><label>Ime i prezime<input name="name" required maxLength={100} defaultValue="Demo kupac" autoComplete="off"/></label><label>E-mail<input name="email" type="email" required maxLength={150} defaultValue="demo@example.com" autoComplete="off"/></label><label>Adresa<input name="address" required maxLength={180} defaultValue="Primjer ulice 12" autoComplete="off"/></label><label>Grad<input name="city" required maxLength={80} defaultValue="Mostar" autoComplete="off"/></label></div><div className="demo-payment"><Check size={18}/><div><strong>Pouzećem — demo</strong><p>Nema kartičnih podataka ni stvarnog plaćanja.</p></div></div><Totals amount={amount}/>{formError&&<p role="alert" className="inline-error">{formError}</p>}<button className="primary-button" type="submit" disabled={!cart.length}>Završi probnu narudžbu<ArrowRight size={18}/></button><button type="button" className="continue-link" onClick={()=>{setCheckoutOpen(false);setCartOpen(true);}}><ArrowLeft size={14}/>Nazad na korpu</button></form></>}</DialogContent></Dialog>

<Dialog open={guideOpen} onOpenChange={setGuideOpen}><DialogContent className="info-dialog" showCloseButton={false}><Close label="Zatvori vodič"/><DialogTitle>Vodič za veličine</DialogTitle><DialogDescription>Orijentacijski prikaz za demo kolekciju. Mjere pojedinog proizvođača mogu se razlikovati.</DialogDescription><table className="size-table"><thead><tr><th>Veličina</th><th>Prsa (cm)</th><th>Struk (cm)</th></tr></thead><tbody>{[['S / 46','90–94','78–82'],['M / 48','94–98','82–86'],['L / 50','98–102','86–90'],['XL / 52','102–106','90–94'],['XXL / 54','106–110','94–98'],['56','110–114','98–102']].map(row=><tr key={row[0]}>{row.map((c,i)=><td key={i}>{c}</td>)}</tr>)}</tbody></table><p>Hlače: oznake 30–38 predstavljaju približan obim struka u inčima. Remeni: 90–110 označava dužinu u centimetrima.</p><p>Izmjerite obim prsa i struka bez zatezanja metra. Za stvarnu trgovinu dodaje se tabela proizvođača.</p></DialogContent></Dialog>
<Dialog open={infoOpen} onOpenChange={setInfoOpen}><DialogContent className="info-dialog" showCloseButton={false}><Close label="Zatvori informacije"/><p className="eyebrow">MOST STUDIO · PRIMJER IZRADE</p><DialogTitle>Vaš brend. Vaša trgovina.</DialogTitle><DialogDescription>Ovo je funkcionalni demo webshopa sa 50 artikala muške odjeće.</DialogDescription><p>Isprobajte pretragu, kategorije, filtere, odabir veličine, korpu i probnu kupovinu. Logo, boje, proizvode i sadržaj prilagođavamo vašem brendu.</p><p>Fotografije su generisane u stilu fotografija iz male radnje. Nazivi, cijene, sastav i dostupnost su ilustrativni.</p><p>Korpa se pamti samo u ovom pregledniku. Podaci probne kupovine ne šalju se trgovcu i ne čuvaju se nakon zatvaranja stranice. Nema stvarne naplate ni dostave.</p><a className="primary-button" href="/#top">Upoznajte MOST Studio<ArrowRight size={17}/></a></DialogContent></Dialog>
<Toaster theme="light" position="bottom-center"/>
</>;}
