import {products,categories,normalize,subtotal,shipping,type CartLine} from './catalog';
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
type Registry={registerTool:(t:Tool,o:{signal:AbortSignal})=>unknown};
const paint=()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));
export function registerShopTools(actions:{search:(q:string,c:string)=>void;getCart:()=>CartLine[];add:(items:CartLine[])=>void}){
const ctx=(document as Document&{modelContext?:Registry}).modelContext;if(!ctx?.registerTool)return()=>{};const lifecycle=new AbortController();
const register=(t:Tool)=>{try{Promise.resolve(ctx.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
register({name:'search_products',title:'Pretraži artikle',description:'Pretraži demo katalog i prikaži rezultate u trgovini.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['Sve',...categories]}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{const v=input as {query?:unknown;category?:unknown};if(!v||typeof v!=='object'||(v.query!==undefined&&typeof v.query!=='string')||(v.category!==undefined&&!['Sve',...categories].includes(String(v.category))))throw new Error('Neispravna pretraga.');const q=String(v.query??''),c=String(v.category??'Sve');actions.search(q,c);await paint();return products.filter(p=>(c==='Sve'||p.category===c)&&normalize(p.name+' '+p.color+' '+p.category).includes(normalize(q))).map(p=>({id:p.id,name:p.name,price:p.price,availableSizes:p.sizes.filter(s=>p.stock[s]>0)}));}});
register({name:'get_cart',title:'Pregled korpe',description:'Pročitaj sadržaj demo korpe i iznose u KM.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({items:actions.getCart(),subtotal:subtotal(actions.getCart()),shipping:shipping(subtotal(actions.getCart())),currency:'BAM'})});
register({name:'add_products_to_cart',title:'Dodaj u korpu',description:'Dodaj odabrane artikle i veličine u demo korpu. Ne naručuje i ne naplaćuje.',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:50,items:{type:'object',properties:{id:{type:'string'},size:{type:'string'},quantity:{type:'integer',minimum:1,maximum:10}},required:['id','size','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{const v=input as {items?:unknown};if(!v||!Array.isArray(v.items)||!v.items.length||v.items.length>50)throw new Error('Nedostaju artikli.');const items=v.items.map((item:unknown)=>{const x=item as CartLine;if(!x||typeof x!=='object'||typeof x.id!=='string'||typeof x.size!=='string'||!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>10)throw new Error('Neispravan artikal.');return{id:x.id,size:x.size,quantity:x.quantity};});actions.add(items);await paint();return{items:actions.getCart(),total:subtotal(actions.getCart())+shipping(subtotal(actions.getCart())),currency:'BAM'};}});
return()=>lifecycle.abort();}
